# Generated by Django 2.1.7 on 2019-04-04 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
        ('InstructorCourse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorcourse',
            name='classNumber',
        ),
        migrations.RemoveField(
            model_name='instructorcourse',
            name='userName',
        ),
        migrations.AddField(
            model_name='instructorcourse',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Course.Course'),
        ),
    ]
