# Generated by Django 2.1.7 on 2019-04-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(default=' ', max_length=20)),
                ('firstName', models.CharField(default=' ', max_length=20)),
                ('lastName', models.CharField(default=' ', max_length=20)),
                ('password', models.CharField(default='password', max_length=20)),
                ('email', models.EmailField(default='', max_length=254)),
                ('title', models.IntegerField(default=0)),
                ('address', models.CharField(default=' ', max_length=30)),
                ('city', models.CharField(default=' ', max_length=20)),
                ('state', models.CharField(default=' ', max_length=20)),
                ('zipCode', models.IntegerField(default=0)),
                ('officeNumber', models.IntegerField(default=0)),
                ('officePhone', models.CharField(default='000-000-0000', max_length=12)),
                ('officeDays', models.CharField(default=' ', max_length=10)),
                ('officeHoursStart', models.IntegerField(default=0)),
                ('officeHoursEnd', models.IntegerField(default=0)),
                ('currentUser', models.BooleanField(default=False)),
            ],
        ),
    ]
