# Generated by Django 2.1.7 on 2019-04-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='officePhone',
            field=models.CharField(default='000-000-0000', max_length=12),
        ),
    ]
