# Generated by Django 2.1.7 on 2019-03-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_auto_20190314_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='accountTitle',
            field=models.TextField(default=''),
        ),
    ]
