# Generated by Django 2.1.7 on 2019-03-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_auto_20190327_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='Accountname',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='Accountid',
        ),
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(default='password', max_length=20),
        ),
    ]
