# Generated by Django 2.1.7 on 2019-03-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_account_accounttitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='accountHP',
            field=models.TextField(default=''),
        ),
    ]
