# Generated by Django 2.1.7 on 2019-03-28 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_auto_20190327_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='title',
            field=models.IntegerField(default=0),
        ),
    ]
