# Generated by Django 2.1.7 on 2019-03-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_account_accounthp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountHP',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='accountName',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='accountTitle',
            field=models.CharField(default='', max_length=10),
        ),
    ]
