# Generated by Django 2.1.7 on 2019-03-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_account_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='currentUser',
            field=models.BooleanField(default=False),
        ),
    ]
