# Generated by Django 2.1.7 on 2019-03-29 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_account_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='Name',
        ),
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='account',
            name='officeDays',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AddField(
            model_name='account',
            name='officeHours',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AddField(
            model_name='account',
            name='officeNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='officePhone',
            field=models.CharField(default='000-000-0000', max_length=10),
        ),
        migrations.AddField(
            model_name='account',
            name='userName',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
