# Generated by Django 2.1.7 on 2019-03-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_auto_20190329_0305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='officeHours',
        ),
        migrations.AddField(
            model_name='account',
            name='city',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='account',
            name='officeHoursEnd',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='officeHoursStart',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='state',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='account',
            name='zipCode',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(default=' ', max_length=30),
        ),
    ]
