# Generated by Django 2.1.7 on 2019-03-31 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_auto_20190329_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='name',
            new_name='firstName',
        ),
        migrations.AddField(
            model_name='account',
            name='lastName',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
