# Generated by Django 2.1.7 on 2019-04-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=20)),
                ('number', models.IntegerField(default=0)),
                ('onCampus', models.BooleanField(default=True)),
                ('classDays', models.CharField(default=' ', max_length=10)),
                ('classHoursStart', models.IntegerField(default=0)),
                ('classHoursEnd', models.IntegerField(default=0)),
            ],
        ),
    ]
