# Generated by Django 2.1.7 on 2019-04-02 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='classDays',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='classHoursEnd',
            field=models.CharField(default='00:00', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='classHoursStart',
            field=models.CharField(default='00:00', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='onCampus',
            field=models.BooleanField(default=True),
        ),
    ]
