# Generated by Django 2.1.7 on 2019-04-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_auto_20190401_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='classHoursEnd',
            field=models.CharField(default='0000', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='classHoursStart',
            field=models.CharField(default='0000', max_length=10),
        ),
    ]
