# Generated by Django 2.1.7 on 2019-04-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0003_auto_20190403_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='classHoursEnd',
            field=models.IntegerField(default='0000', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='classHoursStart',
            field=models.IntegerField(default='0000', max_length=10),
        ),
    ]
