# Generated by Django 2.1.7 on 2019-04-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0004_auto_20190403_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='classHoursEnd',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='classHoursStart',
            field=models.IntegerField(default=0),
        ),
    ]
