# Generated by Django 2.1.7 on 2019-04-07 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Course', '0001_initial'),
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TACourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.Course')),
                ('TA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.Account')),
            ],
        ),
    ]
