# Generated by Django 2.1.7 on 2019-04-05 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionNumber', models.IntegerField(default=0)),
                ('meetingDays', models.CharField(default=' ', max_length=10)),
                ('startTime', models.IntegerField(default=0)),
                ('endTime', models.IntegerField(default=0)),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Course.Course')),
            ],
        ),
    ]
