# Generated by Django 2.1.7 on 2019-03-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateLab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseNumber', models.IntegerField(default=0, max_length=5)),
                ('sectionNumber', models.CharField(default=0, max_length=3)),
                ('meetingDays', models.CharField(default=' ', max_length=10)),
                ('startTime', models.IntegerField(default='00:00', max_length=10)),
                ('endTime', models.IntegerField(default='00:00', max_length=10)),
            ],
        ),
    ]
