# Generated by Django 2.1.7 on 2019-03-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createlab',
            name='courseNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='createlab',
            name='endTime',
            field=models.CharField(default='00:00', max_length=10),
        ),
        migrations.AlterField(
            model_name='createlab',
            name='sectionNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='createlab',
            name='startTime',
            field=models.CharField(default='00:00', max_length=10),
        ),
    ]
