# Generated by Django 2.1.7 on 2019-04-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0002_remove_lab_roomnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='sectionNumber',
            field=models.CharField(default='000', max_length=10),
        ),
    ]
