# Generated by Django 2.1.7 on 2019-04-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0003_auto_20190402_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='endTime',
            field=models.CharField(default='0000', max_length=10),
        ),
        migrations.AlterField(
            model_name='lab',
            name='startTime',
            field=models.CharField(default='0000', max_length=10),
        ),
    ]
