# Generated by Django 2.1.7 on 2019-04-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0005_auto_20190403_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='sectionNumber',
            field=models.IntegerField(default=0),
        ),
    ]
