# Generated by Django 2.1.7 on 2019-04-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0006_auto_20190403_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='courseNumber',
        ),
        migrations.AlterField(
            model_name='lab',
            name='sectionNumber',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
